name: hello world
on: 
  pull_request:
    branches:
        #- dev
        #- qa
         - main
jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Greet the world
        run: echo "Hello, World!"
   
  
