name: Build and Test Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      run: |
        docker build -t my-app-image .
      
    - name: Test Docker image
      run: |
        docker run --name my-app-container -d my-app-image
        # Add commands here to test your application, for example:
        # docker exec my-app-container python3 -m unittest discover
        docker logs my-app-container
        docker stop my-app-container
        docker rm my-app-container
