name: Build an image

on: 
 pull_request:
   branches:
     - main

jobs:
  build:
    runs_on: ubuntu-latest

    steps: 
    -  name: checkout code
       uses: action/checkout@v2

    - name: setup of docker image
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      run: |
        docker build -t my-app-image

     
